[project]
name = "project-name"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]


[tasks]
# This contains a fix to "MassQueryLanguage Release 2024.12.12", correcting a bug in the molecular mass calculation.
install_python_package_from_git= {cmd="pip install git+https://github.com/chasemc/MassQueryLanguage.git@chasemc-patch-1"}

[dependencies]
quarto="==1.6.41" # Don't modify this line
r-base="==4.4.2"
pip=">=25"
python="==3.12"
cytoscape="==3.10.3"


[pypi-dependencies]
numpy=">=2"
tqdm="==4.67.1"
pandas="==2.2.3"
pyteomics="==4.7.5"
IPython="==9.0.2"
nbconvert="==7.16.6"
requests="==2.32.3"
pubchempy="==1.0.4"
rdkit="==2024.9.5"
plotnine="==0.14.5"
matchms="==0.28.2"
massql="==0.0.15"
ipython="==9.0.2"
ipykernel="==6.29.5"
pyopenms="==3.3.0"